import express from "express";

const router = express.Router();

const estados = [
  { sigla: "AC", nome: "Acre" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "RR", nome: "Roraima" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "TO", nome: "Tocantins" },
];

const paises = [
  { code: "AF", nome: "Afeganistão" },
  { code: "ZA", nome: "África do Sul" },
  { code: "AL", nome: "Albânia" },
  { code: "DE", nome: "Alemanha" },
  { code: "AD", nome: "Andorra" },
  { code: "AO", nome: "Angola" },
  { code: "AG", nome: "Antígua e Barbuda" },
  { code: "SA", nome: "Arábia Saudita" },
  { code: "DZ", nome: "Argélia" },
  { code: "AR", nome: "Argentina" },
  { code: "AM", nome: "Armênia" },
  { code: "AU", nome: "Austrália" },
  { code: "AT", nome: "Áustria" },
  { code: "AZ", nome: "Azerbaijão" },
  { code: "BS", nome: "Bahamas" },
  { code: "BD", nome: "Bangladesh" },
  { code: "BB", nome: "Barbados" },
  { code: "BH", nome: "Bahrein" },
  { code: "BE", nome: "Bélgica" },
  { code: "BZ", nome: "Belize" },
  { code: "BJ", nome: "Benin" },
  { code: "BY", nome: "Bielorrússia" },
  { code: "BO", nome: "Bolívia" },
  { code: "BA", nome: "Bósnia e Herzegovina" },
  { code: "BW", nome: "Botsuana" },
  { code: "BR", nome: "Brasil" },
  { code: "BN", nome: "Brunei" },
  { code: "BG", nome: "Bulgária" },
  { code: "BF", nome: "Burkina Faso" },
  { code: "BI", nome: "Burundi" },
  { code: "BT", nome: "Butão" },
  { code: "CV", nome: "Cabo Verde" },
  { code: "CM", nome: "Camarões" },
  { code: "KH", nome: "Camboja" },
  { code: "CA", nome: "Canadá" },
  { code: "QA", nome: "Catar" },
  { code: "KZ", nome: "Cazaquistão" },
  { code: "TD", nome: "Chade" },
  { code: "CL", nome: "Chile" },
  { code: "CN", nome: "China" },
  { code: "CY", nome: "Chipre" },
  { code: "CO", nome: "Colômbia" },
  { code: "KM", nome: "Comores" },
  { code: "CG", nome: "Congo" },
  { code: "CD", nome: "Congo (Rep. Dem.)" },
  { code: "KP", nome: "Coreia do Norte" },
  { code: "KR", nome: "Coreia do Sul" },
  { code: "CI", nome: "Costa do Marfim" },
  { code: "CR", nome: "Costa Rica" },
  { code: "HR", nome: "Croácia" },
  { code: "CU", nome: "Cuba" },
  { code: "DK", nome: "Dinamarca" },
  { code: "DJ", nome: "Djibuti" },
  { code: "DM", nome: "Dominica" },
  { code: "EG", nome: "Egito" },
  { code: "SV", nome: "El Salvador" },
  { code: "AE", nome: "Emirados Árabes Unidos" },
  { code: "EC", nome: "Equador" },
  { code: "ER", nome: "Eritreia" },
  { code: "SK", nome: "Eslováquia" },
  { code: "SI", nome: "Eslovênia" },
  { code: "ES", nome: "Espanha" },
  { code: "SZ", nome: "Essuatíni" },
  { code: "ET", nome: "Etiópia" },
  { code: "FJ", nome: "Fiji" },
  { code: "PH", nome: "Filipinas" },
  { code: "FI", nome: "Finlândia" },
  { code: "FR", nome: "França" },
  { code: "GA", nome: "Gabão" },
  { code: "GM", nome: "Gâmbia" },
  { code: "GH", nome: "Gana" },
  { code: "GE", nome: "Geórgia" },
  { code: "GD", nome: "Granada" },
  { code: "GR", nome: "Grécia" },
  { code: "GT", nome: "Guatemala" },
  { code: "GY", nome: "Guiana" },
  { code: "GN", nome: "Guiné" },
  { code: "GW", nome: "Guiné-Bissau" },
  { code: "GQ", nome: "Guiné Equatorial" },
  { code: "HT", nome: "Haiti" },
  { code: "HN", nome: "Honduras" },
  { code: "HU", nome: "Hungria" },
  { code: "YE", nome: "Iêmen" },
  { code: "IN", nome: "Índia" },
  { code: "ID", nome: "Indonésia" },
  { code: "IQ", nome: "Iraque" },
  { code: "IR", nome: "Irã" },
  { code: "IE", nome: "Irlanda" },
  { code: "IS", nome: "Islândia" },
  { code: "IL", nome: "Israel" },
  { code: "IT", nome: "Itália" },
  { code: "JM", nome: "Jamaica" },
  { code: "JP", nome: "Japão" },
  { code: "JO", nome: "Jordânia" },
  { code: "KE", nome: "Quênia" },
  { code: "KI", nome: "Quiribati" },
  { code: "KW", nome: "Kuwait" },
  { code: "LA", nome: "Laos" },
  { code: "LS", nome: "Lesoto" },
  { code: "LV", nome: "Letônia" },
  { code: "LB", nome: "Líbano" },
  { code: "LR", nome: "Libéria" },
  { code: "LY", nome: "Líbia" },
  { code: "LI", nome: "Liechtenstein" },
  { code: "LT", nome: "Lituânia" },
  { code: "LU", nome: "Luxemburgo" },
  { code: "MK", nome: "Macedônia do Norte" },
  { code: "MG", nome: "Madagascar" },
  { code: "MY", nome: "Malásia" },
  { code: "MW", nome: "Malawi" },
  { code: "MV", nome: "Maldivas" },
  { code: "ML", nome: "Mali" },
  { code: "MT", nome: "Malta" },
  { code: "MA", nome: "Marrocos" },
  { code: "MH", nome: "Ilhas Marshall" },
  { code: "MR", nome: "Mauritânia" },
  { code: "MU", nome: "Maurício" },
  { code: "MX", nome: "México" },
  { code: "FM", nome: "Micronésia" },
  { code: "MZ", nome: "Moçambique" },
  { code: "MD", nome: "Moldávia" },
  { code: "MC", nome: "Mônaco" },
  { code: "MN", nome: "Mongólia" },
  { code: "ME", nome: "Montenegro" },
  { code: "MM", nome: "Myanmar" },
  { code: "NA", nome: "Namíbia" },
  { code: "NR", nome: "Nauru" },
  { code: "NP", nome: "Nepal" },
  { code: "NI", nome: "Nicarágua" },
  { code: "NE", nome: "Níger" },
  { code: "NG", nome: "Nigéria" },
  { code: "NO", nome: "Noruega" },
  { code: "NZ", nome: "Nova Zelândia" },
  { code: "OM", nome: "Omã" },
  { code: "PW", nome: "Palau" },
  { code: "PA", nome: "Panamá" },
  { code: "PG", nome: "Papua Nova Guiné" },
  { code: "PK", nome: "Paquistão" },
  { code: "PY", nome: "Paraguai" },
  { code: "PE", nome: "Peru" },
  { code: "PL", nome: "Polônia" },
  { code: "PT", nome: "Portugal" },
  { code: "GB", nome: "Reino Unido" },
  { code: "CF", nome: "República Centro-Africana" },
  { code: "CZ", nome: "República Tcheca" },
  { code: "DO", nome: "República Dominicana" },
  { code: "RO", nome: "Romênia" },
  { code: "RW", nome: "Ruanda" },
  { code: "RU", nome: "Rússia" },
  { code: "WS", nome: "Samoa" },
  { code: "SM", nome: "San Marino" },
  { code: "LC", nome: "Santa Lúcia" },
  { code: "ST", nome: "São Tomé e Príncipe" },
  { code: "VC", nome: "São Vicente e Granadinas" },
  { code: "KN", nome: "São Cristóvão e Nevis" },
  { code: "SN", nome: "Senegal" },
  { code: "SL", nome: "Serra Leoa" },
  { code: "RS", nome: "Sérvia" },
  { code: "SC", nome: "Seychelles" },
  { code: "SO", nome: "Somália" },
  { code: "LK", nome: "Sri Lanka" },
  { code: "SD", nome: "Sudão" },
  { code: "SS", nome: "Sudão do Sul" },
  { code: "SE", nome: "Suécia" },
  { code: "CH", nome: "Suíça" },
  { code: "SR", nome: "Suriname" },
  { code: "TH", nome: "Tailândia" },
  { code: "TZ", nome: "Tanzânia" },
  { code: "TJ", nome: "Tajiquistão" },
  { code: "TL", nome: "Timor-Leste" },
  { code: "TG", nome: "Togo" },
  { code: "TO", nome: "Tonga" },
  { code: "TT", nome: "Trinidad e Tobago" },
  { code: "TN", nome: "Tunísia" },
  { code: "TM", nome: "Turcomenistão" },
  { code: "TR", nome: "Turquia" },
  { code: "TV", nome: "Tuvalu" },
  { code: "UA", nome: "Ucrânia" },
  { code: "UG", nome: "Uganda" },
  { code: "UY", nome: "Uruguai" },
  { code: "UZ", nome: "Uzbequistão" },
  { code: "VU", nome: "Vanuatu" },
  { code: "VA", nome: "Vaticano" },
  { code: "VE", nome: "Venezuela" },
  { code: "VN", nome: "Vietnã" },
  { code: "ZM", nome: "Zâmbia" },
  { code: "ZW", nome: "Zimbábue" },
];

router.get("/cadastroPaciente", function(req,res) {
    res.render("cadastroPaciente", {
        estados : estados,
        paises : paises
    });
});

export default router;